INSERT INTO categories (id, name, description, parent_id) VALUES (1, 'Product Catalog', 'Danh mục sản phẩm là danh mục gốc của tất cả các sản phẩm', NULL);
INSERT INTO categories (id, name, description, parent_id) VALUES (2, 'Fashion', 'Danh mục thời trang', 1);
INSERT INTO categories (id, name, description, parent_id) VALUES (3, 'Electronics', 'Danh mục đồ điện tử', 1);
INSERT INTO categories (id, name, description, parent_id) VALUES (4, 'Beauty', 'Danh mục đồ làm đẹp', 1);
INSERT INTO categories (id, name, description, parent_id) VALUES (5, 'Housewares', 'Danh mục đồ gia dụng', 1);
INSERT INTO categories (id, name, description, parent_id) VALUES (6, 'Decoration', 'Danh mục đồ trang trí', 1);
INSERT INTO categories (id, name, description, parent_id) VALUES (7, 'Book', 'Danh mục sách', 1);
INSERT INTO categories (id, name, description, parent_id) VALUES (8, 'Stationery', 'Danh mục đồ văn phòng ', 1);
INSERT INTO categories (id, name, description, parent_id) VALUES (9, 'Mother and baby', 'Danh mục đồ cho trẻ nhỏ, bà bầu', 1);
INSERT INTO categories (id, name, description, parent_id) VALUES (10, 'Shoes', 'Danh mục giày dép', 1);
INSERT INTO categories (id, name, description, parent_id) VALUES (11, 'Book bag', 'Danh mục túi sách', 1);
INSERT INTO categories (id, name, description, parent_id) VALUES (12, 'Men Fashion', 'Thời trang nam', 2);
INSERT INTO categories (id, name, description, parent_id) VALUES (13, 'Women Fashion', 'Thời trang nữ', 2);
INSERT INTO categories (id, name, description, parent_id) VALUES (14, 'Men Pants', 'Quần nam', 12);
INSERT INTO categories (id, name, description, parent_id) VALUES (15, 'Men Shirts', 'Áo nam', 12);
INSERT INTO categories (id, name, description, parent_id) VALUES (16, 'Men Underwear', 'Đồ lót nam', 12);
INSERT INTO categories (id, name, description, parent_id) VALUES (17, 'Men Socks', 'Tất nam', 12);
INSERT INTO categories (id, name, description, parent_id) VALUES (18, 'Men Accessories', 'Trang sức nam', 12);
INSERT INTO categories (id, name, description, parent_id) VALUES (19, 'Women Pants', 'Quần nữ', 13);
INSERT INTO categories (id, name, description, parent_id) VALUES (20, 'Women Shirts', 'Áo nữ', 13);
INSERT INTO categories (id, name, description, parent_id) VALUES (21, 'Women Underwear', 'Đồ lót nữ', 13);
INSERT INTO categories (id, name, description, parent_id) VALUES (22, 'Women Socks', 'Tất nữ', 13);
INSERT INTO categories (id, name, description, parent_id) VALUES (23, 'Women Accessories', 'Trang sức nữ', 13);
INSERT INTO categories (id, name, description, parent_id) VALUES (24, 'Mobile and accessories', 'Danh mục điện thoại và các linh kiện điện thoại', 1);
INSERT INTO categories (id, name, description, parent_id) VALUES (25, 'Computers and accessories', 'Danh mục máy tính và các linh kiện máy tính', 1);
INSERT INTO categories (id, name, description, parent_id) VALUES (26, 'TV and Screens', 'TV và màn hình', 3);
INSERT INTO categories (id, name, description, parent_id) VALUES (27, 'Audio Devices', 'Thiết bị âm thanh', 3);
INSERT INTO categories (id, name, description, parent_id) VALUES (28, 'Smart Home Appliances', 'Đồ gia dụng thông minh', 3);
INSERT INTO categories (id, name, description, parent_id) VALUES (29, 'Healthy', 'Danh mục đồ sức khỏe', 1);
INSERT INTO categories (id, name, description, parent_id) VALUES (30, 'Skin Care', 'Chăm sóc da', 4);
INSERT INTO categories (id, name, description, parent_id) VALUES (31, 'Hair Care', 'Chăm sóc tóc', 4);
INSERT INTO categories (id, name, description, parent_id) VALUES (32, 'Oral Care', 'Vệ sinh răng miệng', 4);
INSERT INTO categories (id, name, description, parent_id) VALUES (33, 'Beauty Tools', 'Dụng cụ làm đẹp', 4);
INSERT INTO categories (id, name, description, parent_id) VALUES (34, 'Body Care', 'Chăm sóc cơ thể', 4);
INSERT INTO categories (id, name, description, parent_id) VALUES (35, 'Kitchen Appliances', 'Thiết bị nhà bếp', 5);
INSERT INTO categories (id, name, description, parent_id) VALUES (36, 'Cleaning Tools', 'Dụng cụ vệ sinh', 5);
INSERT INTO categories (id, name, description, parent_id) VALUES (37, 'Baby Care', 'Chăm sóc em bé', 9);
INSERT INTO categories (id, name, description, parent_id) VALUES (38, 'Maternity Products', 'Sản phẩm cho mẹ', 9);
INSERT INTO categories (id, name, description, parent_id) VALUES (39, 'Baby Toys', 'Đồ chơi trẻ em', 9);
INSERT INTO categories (id, name, description, parent_id) VALUES (40, 'Baby Clothes', 'Quần áo trẻ em', 9);
INSERT INTO categories (id, name, description, parent_id) VALUES (41, 'Men Shoe', 'Giày nam', 10);
INSERT INTO categories (id, name, description, parent_id) VALUES (42, 'Women Shoe', 'Giày nữ', 10);
INSERT INTO categories (id, name, description, parent_id) VALUES (43, 'Kid Shoe', 'Giày trẻ em', 10);
INSERT INTO categories (id, name, description, parent_id) VALUES (44, 'Sport Shoe', 'Giày thể thao', 10);
INSERT INTO categories (id, name, description, parent_id) VALUES (45, 'Backpack', 'Ba lô', 11);
INSERT INTO categories (id, name, description, parent_id) VALUES (46, 'Handbag', 'Túi xách tay', 11);
INSERT INTO categories (id, name, description, parent_id) VALUES (47, 'Travel Bag', 'Túi du lịch', 11);
INSERT INTO categories (id, name, description, parent_id) VALUES (48, 'Smartphone', 'Điện thoại thông minh', 24);
INSERT INTO categories (id, name, description, parent_id) VALUES (49, 'Tablet', 'Máy tính bảng', 24);
INSERT INTO categories (id, name, description, parent_id) VALUES (50, 'Phone Accessories', 'Phụ kiện điện thoại', 24);
INSERT INTO categories (id, name, description, parent_id) VALUES (51, 'Laptop', 'Máy tính xách tay', 25);
INSERT INTO categories (id, name, description, parent_id) VALUES (52, 'Desktop PC', 'Máy tính để bàn', 25);
INSERT INTO categories (id, name, description, parent_id) VALUES (53, 'Computer Accessories', 'Phụ kiện máy tính', 25);
INSERT INTO categories (id, name, description, parent_id) VALUES (54, 'Computer Components', 'Linh kiện máy tính', 25);
INSERT INTO categories (id, name, description, parent_id) VALUES (55, 'Medical Supplies', 'Vật tư y tế', 29);
INSERT INTO categories (id, name, description, parent_id) VALUES (56, 'Fitness Equipment', 'Thiết bị thể dục', 29);
INSERT INTO categories (id, name, description, parent_id) VALUES (57, 'Vitamins and Supplements', 'Vitamin và thực phẩm bổ sung', 29);
INSERT INTO categories (id, name, description, parent_id) VALUES (58, 'Writing Instruments', 'Dụng cụ viết', 8);
INSERT INTO categories (id, name, description, parent_id) VALUES (59, 'Paper Products', 'Sản phẩm giấy', 8);
INSERT INTO categories (id, name, description, parent_id) VALUES (60, 'Office Supplies', 'Văn phòng phẩm', 8);
INSERT INTO categories (id, name, description, parent_id) VALUES (61, 'School Supplies', 'Dụng cụ học tập', 8);
